# Generated by Django 4.2.1 on 2023-05-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(unique=True, verbose_name='ID вопроса')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ на вопрос')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания вопроса')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['question_id'], name='question_id_idx')],
            },
        ),
    ]
