version: '2.7'

services:
  db:
    image: postgres:14.0-alpine
    restart: on-failure
    volumes:
      - bewisedata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: Bewise
    ports:
      - "5432:5432"
    hostname: db
    container_name: BewiseDB
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "Bewise", "-U", "postgres" ]
      timeout: 5s
      interval: 5s
      retries: 10

  webapp:
    build: .
    container_name: django
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      "db":
        condition: service_healthy
    tty: true
    command:
      bash -c "python manage.py migrate api && python manage.py runserver 0.0.0.0:8000"

volumes:
  bewisedata: